obstacle_range: 2.5
raytrace_range: 3.0

footprint: [[0.4, -0.353], [0.4, 0.353], [-0.4, 0.353], [-0.4, -0.353]]

publish_frequency: 1.0

obstacle_layer:
  observation_sources: merged_laser
  merged_laser: {sensor_frame: robot_base_footprint, data_type: LaserScan, topic: /robot/merged_laser/scan_multi, marking: true, clearing: true}

static:
  map_topic: /map
  subscribe_to_updates: true