global_costmap:
  global_frame: robot_odom
  robot_base_frame: robot_base_footprint
  update_frequency: 5.0
  static_map: False
  rolling_window: True
  width: 100
  height: 100

  footprint_padding: 0.1

  inflation_layer:
    enabled : true
    inflation_radius: 0.5
    cost_scaling_factor: 1

  plugins:
  - {name: obstacle_layer,   type: "costmap_2d::VoxelLayer"}
  - {name: inflation_layer,   type: "costmap_2d::InflationLayer"}